apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: safe-gateway
spec:
  # Use the built-in Google class (Global External Load Balancer)
  gatewayClassName: gke-l7-global-external-managed 
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
