apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: safe-gateway
spec:
  gatewayClassName: nginx # This tells K8s to use the Nginx Fabric you just installed
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All
