experimental:
  kubernetesGateway:
    enabled: true

providers:
  kubernetesGateway:
    enabled: true
  kubernetesIngress:
    enabled: false

ports:
  web:
    port: 80
    expose:
      default: true

  websecure:
    port: 443
    expose:
      default: true

  gateway:
    port: 8000
    expose:
      default: false
