apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: safe-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: safe-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: safe-backend-service
            port:
              number: 5000
